:toc:
:toc-placement!:

:note-caption: :information_source:
:tip-caption: :bulb:
:important-caption: :heavy_exclamation_mark:
:warning-caption: :warning:
:caution-caption: :fire:

= Ansible Study Group Labs
Ron Kurr <rkurr@jvmguy.com>


toc::[]

== Overview
This project is a collection of hands on labs showcasing the use of Ansible.  Unlike other study groups, the learners will have to solve problems with minimal guidance.

TIP: Each lab exercises what was showcased in the video assignments so many of your questions are probably already answered in the video.

IMPORTANT: Each lab builds on the prior ones, so if you are absent from a meeting you need to finish the lab before you can begin any new ones.

== Prerequisites

* an https://aws.amazon.com/[AWS] account
* an SSH client
* familiarity with https://aws.amazon.com/ec2/[EC2]

IMPORTANT: we will be using the same EC2 instances for the labs so always have your SSH key available when we meet.

TIP: Learners running Windows have had good success with http://gitforwindows.org/[Git BASH].

== Lab 01: Setting Up The Testing Environment

In order to give Ansible inventory to work on, we need to setup several small EC2 instances.  In your Amazon account, create the following:

* [ ] a new SSH key pair
* [ ] an Ubuntu `t2.nano` instance named Ansible Control
* [ ] an Ubuntu `t2.nano` instance named Alpha
* [ ] an Ubuntu `t2.nano` instance named Bravo
* [ ] an Amazon Linux `t2.nano` instance named Charlie
* [ ] an Amazon Linux `t2.nano` instance named Delta

IMPORTANT: ensure that the security group on the instances allows inbound SSH access (port 22).

TIP: Store your SSH keys on a USB stick so you can use different computers to connect to your control instance.

CAUTION: Remember to not use your root account when setting things up.  An Administrator IAM account is highly recommended.


Ansible uses SSH so we need to verify SSH is working as required.

* [ ] copy the private half of your SSH key to the control box
* [ ] from the control box, ensure you can SSH into Alpha
* [ ] from the control box, ensure you can SSH into Bravo
* [ ] from the control box, ensure you can SSH into Charlie
* [ ] from the control box, ensure you can SSH into Delta
* [ ] stop all of your instances

TIP: The `scp` command can be used to upload the key file.

IMPORTANT: SSH is very picky about file permissions so remember to set the proper permissions on the key prior to use.

== Lab 02: Installing Ansible

== Lab 03: Configuring Ansible

== Lab 04: Understanding Inventory

== License and Credits
This project is licensed under the https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode[Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License].
