:toc:
:toc-placement!:

:note-caption: :information_source:
:tip-caption: :bulb:
:important-caption: :heavy_exclamation_mark:
:warning-caption: :warning:
:caution-caption: :fire:

= Lab 01: Setting Up The Testing Environment
Ron Kurr <rkurr@jvmguy.com>


toc::[]

== Overview
There are many ways to solve the problems presented in the lab.  These solutions are known to work, but you may have found alternative solutions.

IMPORTANT: Only refer to these solutions if you are stuck and are failing to make progress.  The best way to learn is to find the information yourself and apply it.

== Set SSH Key Permissions
----
chmod 0400 AnsibleStudyGroup.pem
----

== SSH into Ansible Control
----
ssh -i AnsibleStudyGroup.pem ubuntu@34.12.15.121
----
IMPORTANT: the ip address will be different for your EC2 instance

== Copy the private half of the SSH key to Ansible Control
----
scp -i AnsibleStudyGroup.pem AnsibleStudyGroup.pem ubuntu@24.12.15.121:
----
IMPORTANT: the trailing `:` is important as it tells `scp` to place the file into the home directory

== From Ansible Control, SSH into the Alpha and Bravo
----
ssh -i AnsibleStudyGroup.pem ubuntu@11.22.33.44
----
IMPORTANT: replace the ip address with `Alpha` and `Bravo` private ip addresses

== From Ansible Control, SSH into the Charlie and Delta
----
ssh -i AnsibleStudyGroup.pem ec2-useru@11.22.33.44
----
IMPORTANT: replace the ip address with `Charlie` and `Delta` private ip addresses

== License and Credits
This project is licensed under the https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode[Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License].
